import { headers } from "next/headers";
import "./globals.css";
import MyContext  from "@/Helper/Context";

export const metadata = {
  title: "Uzair React",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <MyContext>
          {children}
        </MyContext>
      </body>
    </html>
  );
}
